### ISSUE TITLE
Make loading indicator available in status bar

### ISSUE THREAD

**Issue by MattCheetham** [3sidedcube/iOS-ThunderRequest#6]
We used to have the loading indicator in the status bar spin whilst any requests were going on but we removed it when watchOS came out.

We should add it back in and wrap it in an if statement and maybe even give it an info.plist option to enable/disable it. 

I think it's important and helps establish when things like delta publishes are finished.

Interested on your thoughts @simonmitchell and @joeltrew

**Comment by simonmitchell** [comment]
I agree with this, and the implementation suggested! Both the if statement and the info.plist override :) bear in mind we do/will have support in the framework for OSX as well so that'll need to be taken into account on the if-statement side!

**Comment by MattCheetham** [comment]
Done
