### ISSUE TITLE
App Store Rejection

### ISSUE THREAD

**Issue by MattCheetham** [3sidedcube/iOS-ThunderRequest#9]
> Your app uses or references the following non-public APIs:
> 
> parentAnnotation, 
> serviceIdentifier, 
> setParentAnnotation:
> 
> The use of non-public APIs is not permitted on the App Store because it can lead to a poor user experience should these APIs change.

**Comment by MattCheetham** [comment]
I'm not familiar with the OAuth flow so not sure of a suitable replacement for `serviceIdentifier`.

How about `oAuthServiceIdentifier` or `authIdentifier`

@simonmitchell you might have some better ideas.

**Comment by simonmitchell** [comment]
It's not so much used for the actual OAuth flow, simply for storing the credentials in the keychain once it has received them (And retrieving them later). `authIdentifier` is my preferred option out of those, yet to think of anything better.

**Comment by MattCheetham** [comment]
I'm going to go with authIdentifier for now as it is least likely to conflict with Apple I guess. Happy to re-open later if we have a better idea

**Comment by simonmitchell** [comment]
Fine with me! :)
